spring:
  application:
    name: springstarter

  thymeleaf:
    encoding: UTF-8
    cache: false
    check-template-location: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  h2:
    console:
      enabled: true   # ? ?? ???
      path: /db-console  # ? ??? ?? ??
      settings:
        trace: false
        web-allow-others: true

  datasource:
    password: password
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:file:./db/bookdb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
